### ISSUE TITLE
BMI Calculation

### ISSUE THREAD

**Issue by andyferriby** [Jackson-S/weight-tracker#1]
Just had a look at your app using my own height which is 1.76 meters... and my weight is 63.2KG's... The app must have a calculation error as its returning that im obese, which i defo aint. The BMI for my body should be in the region of 19-25.

Healthy weight range for your height:
59.9kg - 81kg

**Comment by Jackson-S** [comment]
Hey Andy. 
I just checked out the iOS app and WatchOS app with those same measurements in the simulator and it reports a BMI on 20.6 which is categorized as normal.

There's not a whole lot of information for me to go off but some possibilities are:
- There might be a unit conversion error, though you gave me those measurements in metric and the back end is all metric so unless I've messed up there should be no conversion.
- The Apple watch can only access two weeks of health kit data and so height has to be regularly updated (I can't remember if I ever fixed this, it's been a while since I worked on this project).
- You didn't give all permissions to HealthKit (This was mostly a project for myself, so I didn't deal with these situations as thoroughly as I probably should have)
- Something messed up on the front end and it didn't update the values correctly.

If you watch for error messages when you run the app then you might see something has gone horribly wrong on the back end. Most things should print an error.

Sorry I couldn't be of more help. If you have any more info just let me know.
